export * from './register-form.interface';
export * from './login-form.interface';
export * from './login-response.interface';
export * from './user-paginated.interface';
export * from './user-page.interface';
export * from './user.interface';
export * from './doctor.interface';
export * from './hospital.interface';
export * from './data-document.interface';
export * from './data-model-document.interface';
export * from './hospitals-api.interface';
export * from './hospital-api.interface';
export * from './hospitals-api-search.interface';
export * from './sweet-alert-result.interface';
export * from './doctor-api.interface';
export * from './doctors-api.interface';
export * from './doctors-api-data.interface';
export * from './hospital-response.interface';

